<a href="https://colab.research.google.com/github/tomasplsek/AstroML/blob/main/01_uvod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Machine learning for astronomers in Python**




- 6-7 lectures
- 6 hands-on sessions
- final project

<div style="">
<img src="https://www.physics.muni.cz/~plsek/img.jpeg" height="160px" align="right">

<img src="https://cdn.muni.cz/media/3289673/matejkosiba.jpg?mode=crop&center=0.53,0.57&rnd=132563180850000000&width=179" height="160px" align="right">

<img src="https://cdn.muni.cz/media/3291288/toastm.jpg?mode=crop&center=0.5,0.5&rnd=132569108280000000&width=179" height="160px" align="right">

\\
### **Timetable**
16.9. - 1st lecture\
23.9. - Tomáš: *Intro to Colab / Jupyter*\
30.9. - Dean's leave\
7.10. - 2nd lecture\
14.10. - \
21.10. - 3rd lecture\
28.10. - \
4.11. - 4th lecture\
11.11. - \
18.11. - 5th lecture\
25.11. - Tomáš: *Into to neural networks*\
2.12. - 6th lecture\
9.12. - \
16.12. - 7th lecture\
23.12. - ???


</div>

> **Tomáš Plšek**
> <br><br>
> email: <a href="mailto:plsek@physics.muni.cz">plsek@physics.muni.cz</a>\
> github: [tomasplsek](https://github.com/tomasplsek)\
> web: [physics.muni.cz/~plsek](https://www.physics.muni.cz/~plsek/)\
> office: [building 8 (math), 4th floor, last door to the left](https://is.muni.cz/auth/kontakty/mistnost?id=10454)

<br>

# 1. hands-on session: **Intro to Colab / Jupyter**

## **Contents**



1.   What is machine learning?
2.   Hardware / software
3.   Google colab / Conda + Jupyter
4.   "Hello world" of ML
5.   What can I do with ML?



## **What is Machine learning?**




### **Why now?**
1957 - **Perceptron** (Frank Rosenblatt)\
1967 -  **Nearest neightbor algorithm**\
...\
1997 - Deep Blue (Chess)\
2016 - Alpha Go


<img src="https://raw.githubusercontent.com/tomasplsek/AstroML/main/figures/cpu_gpu_tpu.png?token=AIISSC6E4L5CFEO6GYOF3OLBITH6E" width="460px" align="right">

## **Hardware**

*   **CPU** = *central processing unit*\
    \- in every computer / mobile phone\
    \- scalar operations\
    \- multiple cores / threads (parallelizable)\
    \- Intel, AMD

<br>

<img src="https://raw.githubusercontent.com/tomasplsek/AstroML/main/figures/cpu_gpu_tpu.jpg?token=AIISSC3T67EOSR7OIN7BTQDBITH2C" width="460px" align="right">


*   **GPU** = *graphical processing unit*\
    \- vector operations\
    \- dedicated or integrated on CPU\
    \- graphics and games (DirectX)\
    \- NVIDIA, AMD

<br>

*   **TPU** = *tensor processing unit*\
    \- tensor operations\
    \- developed by Google for Tensorflow\
    \- narrow utilization field

<br>




## **Software**

Libraries for comunication with GPU:

<img src="https://www.nvidia.com/etc/designs/nvidiaGDC/clientlibs_base/images/NVIDIA-Logo.svg" height="50px" align="right">

*   CUDA = NVIDIA libraries ([toolkit](https://developer.nvidia.com/cuda-toolkit-archive), [cuDNN](https://developer.nvidia.com/rdp/cudnn-download))\
    \- GPU acceleration (Win & Linux)\
    \- lower level

<br>

Higher level libraries are being developed mostly for Python:

<img src="https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png" height="50px" align="right">

*   [scikit-learn](https://scikit-learn.org/stable/)\
    \- set of general ML tools

<img src="https://www.gstatic.com/devrel-devsite/prod/v509a5f4800978e3ce5a1a5f2c1483bd166c25f20fdb759fe97f6131b7e9f1f00/tensorflow/images/lockup.svg" height="50px" align="right">

*   [tensorflow](https://www.tensorflow.org/)\
    \- matrix and tensor computations\
    \- using CUDA and GPU ([install](https://www.tensorflow.org/install/gpu), [setup](https://www.tensorflow.org/guide/gpu))

<img src="https://keras.io/img/logo.png" height="50px" align="right">

*   [keras](https://keras.io/)\
    \- on top of tensorflow\
    \- neural networks (dense & convolutional layers)

*   others: [pyTorch](https://pytorch.org/), Theano

<br>

Programing environments:

<div style="display:table">

<img src="https://colab.research.google.com/img/colab_favicon_256px.png" height="90px" align="right">

<img src="https://jupyter.org/assets/main-logo.svg" height="90px" align="right" style="margin-right:100px">

</div>


*   [Conda](https://docs.conda.io/en/latest/) + [Jupyter](https://jupyter.org/) notebook/lab

*   Google colab

## **Google Colab**

- plenty of preinstalled packages (```numpy```, ```scipy```, ```matplotlib```, ```keras```, ```tensorflow```...)
- new packages are easy to install: ```!pip install corner```
- shell commands ```!```
- [magical commands](https://ipython.readthedocs.io/en/stable/interactive/magics.html) ```%```
- include markdown or HTML blocks
- GPU / TPU acceleration
- access to notebooks and files from **Google drive** and **GitHub**
- share notebooks
- get help

In [ ]:
import tensorflow as tf
from keras.layers import Dense

In [ ]:
!pip install corner

In [ ]:
!ls

drive  file.txt  sample_data


In [ ]:
!echo "nic" > file.txt

In [ ]:
%matplotlib inline

In [ ]:
%pylab

Using matplotlib backend: agg
Populating the interactive namespace from numpy and matplotlib


In [ ]:
import time

In [ ]:
def fun():
    time.sleep(3)
    print("a")
    time.sleep(3)

%time fun()

a
CPU times: user 27.9 ms, sys: 3.67 ms, total: 31.6 ms
Wall time: 6.01 s


In [ ]:
%timeit -r 10 time.sleep(1)

1 loop, best of 10: 1 s per loop


### Heading
#### Heading 2

**bold**

*italic*

```
code
```

```python
from numpy import sin
```

[link](https://scikit-learn.org/)

![](https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png)


> block



1.   ordered list
2.   ...



*   unordered list
*   ...

---

```html
<img src="https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png" height="150px" align="right">
```

<img src="https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png" height="100px" align="right">

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [101]:
import numpy as np
np.array?

## **Conda + Jupyterlab**

## **"Hello world" of ML**

In [15]:
a = 1
b = 4.2
c = "word"
d = [1, 2, 3]
def fun(): pass
import numpy

for i in [a,b,c,d,fun,trida,numpy]:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'function'>
<class 'type'>
<class 'module'>


In [8]:
import numpy as np

In [26]:
a = np.array([1, 2, 3])
b = [1, 2, 3]

In [28]:
type(a), type(b)

(numpy.ndarray, list)

### **task 1:** compute sum of list

a = [1, 2, 3, ...., 1000]\
%timeit sum(a)

In [3]:
def sum_list(a):
    x = 0
    for i in a:
        x += i
    return x

In [4]:
a = [i for i in range(1000)]

In [5]:
%timeit sum_list(a)

10000 loops, best of 5: 42.9 µs per loop


In [6]:
%timeit sum(a)

100000 loops, best of 5: 6.52 µs per loop


In [16]:
b = np.array(a)

In [17]:
type(a), type(b)

(int, numpy.ndarray)

In [18]:
%timeit b.sum()

The slowest run took 2981.21 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.01 µs per loop


In [19]:
a = [i for i in range(1000)]
b = [i for i in range(1000)]

def multiply_lists(a,b):
    c = []
    for i,j in zip(a,b):
        c.append(i * j)
    return c

In [44]:
%timeit multiply_lists(a,b)

10000 loops, best of 5: 131 µs per loop


In [45]:
A = np.array(a)
B = np.array(b)

In [47]:
%timeit A * B

The slowest run took 23.03 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.39 µs per loop


In [51]:
a = np.array([[1,2,3], [4,5,6]])

b = np.array([[7,8,9], [10,11,12]])

%timeit np.dot(a,b.T)

The slowest run took 17.30 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.65 µs per loop


In [21]:
import tensorflow as tf

In [22]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

%timeit c = tf.matmul(a, b)

The slowest run took 17.18 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 39.3 µs per loop


In [90]:
a = np.random.randint(10, size=(3,3,3))
b = np.random.randint(10, size=(3,3,3))
a.shape

(3, 3, 3)

In [100]:
a

array([[[4, 0, 5],
        [5, 7, 0],
        [1, 6, 3]],

       [[0, 3, 0],
        [2, 0, 7],
        [3, 4, 9]],

       [[5, 6, 7],
        [6, 2, 6],
        [9, 5, 1]]])

In [96]:
np.dot(a,b)

array([[[[ 61,  15,  29],
         [ 42,  16,  13],
         [ 63,  10,  63]],

        [[ 59,  63,   5],
         [ 50,  27,  31],
         [ 56,  56,  63]],

        [[ 36,  63,  16],
         [ 51,  10,  23],
         [ 46,  54,  52]]],


       [[[  6,  27,   0],
         [ 15,   3,   9],
         [  9,  24,  12]],

        [[ 53,  21,  37],
         [ 48,   8,  11],
         [ 63,  14,  63]],

        [[ 80,  63,  48],
         [ 83,  16,  27],
         [ 96,  50, 100]]],


       [[[ 92,  75,  40],
         [ 87,  26,  35],
         [102,  62, 108]],

        [[ 88,  36,  36],
         [ 64,  26,  24],
         [ 90,  28,  92]],

        [[ 96,  48,  14],
         [ 58,  41,  34],
         [ 85,  42,  90]]]])

In [99]:
a.dot(b)

array([[[[ 61,  15,  29],
         [ 42,  16,  13],
         [ 63,  10,  63]],

        [[ 59,  63,   5],
         [ 50,  27,  31],
         [ 56,  56,  63]],

        [[ 36,  63,  16],
         [ 51,  10,  23],
         [ 46,  54,  52]]],


       [[[  6,  27,   0],
         [ 15,   3,   9],
         [  9,  24,  12]],

        [[ 53,  21,  37],
         [ 48,   8,  11],
         [ 63,  14,  63]],

        [[ 80,  63,  48],
         [ 83,  16,  27],
         [ 96,  50, 100]]],


       [[[ 92,  75,  40],
         [ 87,  26,  35],
         [102,  62, 108]],

        [[ 88,  36,  36],
         [ 64,  26,  24],
         [ 90,  28,  92]],

        [[ 96,  48,  14],
         [ 58,  41,  34],
         [ 85,  42,  90]]]])

In [88]:
%timeit np.dot(a,b)

1 loop, best of 5: 12.7 s per loop


In [93]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 61,  15,  29],
        [ 59,  63,   5],
        [ 36,  63,  16]],

       [[ 15,   3,   9],
        [ 48,   8,  11],
        [ 83,  16,  27]],

       [[102,  62, 108],
        [ 90,  28,  92],
        [ 85,  42,  90]]])>

In [89]:
%timeit tf.matmul(a,b)

10 loops, best of 5: 52 ms per loop


### Change to GPU

In [1]:
import tensorflow as tf

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]